### ISSUE TITLE
这个脚本用不好

### ISSUE THREAD

**Issue by 623034345** [klaus01/KLGenerateSpamCode#1]
运行老是提示-deleteComments不存在
Program ended with exit code: 1
其他的也一样  感觉我用的方法不对  有联系方式吗?

**Comment by klaus01** [comment]
你是如何运行的？

**Comment by 623034345** [comment]
直接设置-deleteComments  然后运行

**Comment by klaus01** [comment]
哦，参数这块我说漏了一点，`工程源代码绝对路径`参数是必填的，`参数1`必须得是`工程源代码绝对路径`，之后的参数是选填。

**Comment by 623034345** [comment]
是文件夹的绝对路径 还是.project文件的绝对路径

**Comment by klaus01** [comment]
源代码文件夹的

**Comment by 623034345** [comment]
修改完项目名以后 Objective-C Bridging header 缺失  直接没有这一项了0.0

**Comment by klaus01** [comment]
需要手动改下这个文件的名字。

目前`*.entitlements、*-Bridging-Header.h、*-Swift.h、Podfile 中的 target 名称`这些还需要手动修改。

**Comment by 623034345** [comment]
有没有博客文章? 发个链接看看老哥

**Comment by klaus01** [comment]
不好意思，木有
