### ISSUE TITLE
改类名的时候,有cocopods的xcworkspace文件打不开了

### ISSUE THREAD

**Issue by hms111111** [klaus01/KLGenerateSpamCode#13]
不知道怎么解决啊?

**Comment by klaus01** [comment]
发下你的工程目录树结构看下呢。

我的工程也用了 cocoapods 的，这个帖子中有我的目录结构可参考。
https://github.com/klaus01/KLGenerateSpamCode/issues/9#issuecomment-375892020

**Comment by klaus01** [comment]
`xcworkspace`打不开有什么提示没？或者发下修改前和修改后的`xcworkspace`我对比看下。

**Comment by vitasapple** [comment]
打开文件 /Users/jinniu/Desktop/信吧/IDCardManager/TheThird/NewRealName_SDK/include/Globaltypedef.h 失败：The file “Globaltypedef.h” couldn’t be opened using text encoding Unicode (UTF-8).

可是信吧是我另一个项目，我改的明明不是它，路径也设置的对的……

**Comment by klaus01** [comment]
@vitasapple 你这个是修改类名后打开`xcworkspace`出现的提示？

**Comment by xiaohuahao** [comment]
我也遇到同样的问题，“打开文件 /Users/renren/Desktop/ann/pop/ios_branch_li/MIT/Frame/cardcore/exidcard.h 失败：The file “exidcard.h” couldn’t be opened using text encoding Unicode (UTF-8).”，路径什么都是对的。

**Comment by klaus01** [comment]
@xiaohuahao 第三方库的文件最好不要修改，建议把 pop 目录加入`-ignoreDirNames`
