### ISSUE TITLE
1.工程中含有pch文件的，无法替换；2.if ([url hasPrefix:@"//"]) 会被截取。。。

### ISSUE THREAD

**Issue by GKman6657** [klaus01/KLGenerateSpamCode#14]

**Comment by zuqiu123** [comment]
还有修改类名的时候会将文件报红丢失,还有垃圾代码显示成功导入进去基本都是错的,请问如何改善

**Comment by klaus01** [comment]
@zuqiu123 
1. 会有一些报红，这是修改后工程文件中的文件名与实际文件名对不上。修改下工程中的文件名，或修改下实际文件名，对应上及可。如果文件比较多的话，可能比较麻烦。工具支持的情况比较少。
1. 删除报错的垃圾代码。因是字符串匹配的原因，垃圾代码的生成和代码写法有很大的关系，所以可能会有很多报错的情况。

**Comment by 1097171985** [comment]
你这个 能增加修改里面的文件夹  以及 宏 吗？

**Comment by klaus01** [comment]
@1097171985 
修复文件夹名称吗？

修改“宏”没必要，因为编译后是没有宏的，宏的内容都被替换进代码了。

**Comment by BaHui** [comment]
1.在修改项目名称时, 路径应该是.xcodeproj同一级别的文件夹作为项目路径? 还是.xcodeproj上一级作为项目路径? 
我分别试了一下:
1.选.xcodeproj的上一级文件夹作为路径, 但是只是修改了文件夹的名字, 内部项目的名字没有发生变化.
2.选.xcodeproj同级别的文件夹作为路径, 项目修改了, 但是类似.pch, xxx-Bridging-Header, xxx.xcdatamodeld可不可以也跟着变, 目前我试的没变, 想要改变, 要怎么做一下? ^.^

**Comment by klaus01** [comment]
是`2 同级路径`。

.pch, xxx-Bridging-Header, xxx.xcdatamodeld 这些文件没有改，只有你自己 Fork 一份代码改改了。

**Comment by klaus01** [comment]
xx
