### ISSUE TITLE
你好，垃圾代码生成后不是直接到项目对应的.h和.m文件中吗

### ISSUE THREAD

**Issue by lanchangbin** [klaus01/KLGenerateSpamCode#15]
![image](https://user-images.githubusercontent.com/20454288/39126285-824d30b8-4734-11e8-9341-5edbeebd3d0c.png)
![image](https://user-images.githubusercontent.com/20454288/39126298-8b0febe6-4734-11e8-8192-8a64d5c64374.png)
不能直接生成到项目文件中吗
![image](https://user-images.githubusercontent.com/20454288/39126317-9ab2da36-4734-11e8-91e1-53443cc419a0.png)空文件

**Comment by klaus01** [comment]
不能。
主要是直接生成到项目中需要修改工程文件内容，担心把工程文件搞坏。
所以就生成到指定的目录，再拖放到工程中。
