### ISSUE TITLE
打开工程文件 /Users/zhangdongpo/Documents/ModifyTest/ModifyTest.xcodeproj/project.pbxproj 失败：The file “project.pbxproj” couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by zhangdongpo** [klaus01/KLGenerateSpamCode#16]
一直说打开工程文件失败

**Comment by klaus01** [comment]
可以把工程发到我的邮箱么？

**Comment by zhangdongpo** [comment]
明天我去公司发你

**Comment by YZhouHome** [comment]
怎么解决的，我这也是同样的问题

**Comment by YZhouHome** [comment]
换一下顺序就好了，先修改文件前缀，后修改工程名

**Comment by zhangdongpo** [comment]
@YZhouHome 没用的，换了顺序也没办法修改工程的名字。

**Comment by klaus01** [comment]
@zhangdongpo 收到你的工程了。

我下载解压后执行
![image](https://user-images.githubusercontent.com/338228/39289614-708531dc-495f-11e8-99c5-517826c71821.png)
后，能正常打开`~/Downloads/ModifyTest/nameTest.xcodeproj`

**Comment by zhangdongpo** [comment]
@klaus01 我再试试

**Comment by Kingson** [comment]
参数的顺序会影响执行结果？

**Comment by klaus01** [comment]
@Kingson 不会。

**Comment by Kingson** [comment]
@klaus01 好，谢谢

**Comment by arr0813** [comment]
你好，我不勾选-modifyProjectName勾选-modifyClassNamePrefix，可以修改前缀；但是同时勾选-modifyProjectName和-modifyClassNamePrefix就会报这个错误，请问怎么修改？
