### ISSUE TITLE
imageClick 求详细 教程

### ISSUE THREAD

**Issue by jonsnowwinterfell** [klaus01/KLGenerateSpamCode#17]
能够给个截图  这下面   是什么。。  除了安装  brew install imagemagick  下面 是怎么操作的 实在不知道
// find . -iname "*.png" -exec echo {} \; -exec convert {} {} \;
// or
// find . -iname "*.png" -exec echo {} \; -exec convert {} -quality 95 {} \;

**Comment by klaus01** [comment]
<img width="782" alt="20180425203915" src="https://user-images.githubusercontent.com/338228/39246336-d968681e-48c8-11e8-8a80-bf2d405cccae.png">
这样执行命令，就会将`~/Documents/work/git/SJApp`目录及子目录下的所有`png`文件都压缩一下。

**Comment by jonsnowwinterfell** [comment]
大神QQ 号多少

**Comment by jonsnowwinterfell** [comment]
感谢 搞定了   thx ~
