### ISSUE TITLE
UITests，UITest文件好像没有修改

### ISSUE THREAD

**Issue by Wougle** [klaus01/KLGenerateSpamCode#2]
大神，很佩服你写的这脚本；但是我发现UITests，UITest文件好像没有修改，可以的话希望大神能够解决这个问题。

**Comment by klaus01** [comment]
因我们的工程都没有使用 Test ，所以我没有支持。
如果你们的 UITest 没有实际功能或并未使用，建议把 UITest 删除吧。
换个角度想，主包已经测试好了，马甲包没必要再测了吧😁

**Comment by Wougle** [comment]
嗯嗯，谢谢大神回复～
