### ISSUE TITLE
使用 ImageMagick 对 png 图片做轻量压缩失败

### ISSUE THREAD

**Issue by xiaojie111** [klaus01/KLGenerateSpamCode#21]
使用 ImageMagick 对 png 图片做轻量压缩，及不损失图片质量，又可改变图片文件 hash 值。方法：

安装 ImageMagick，brew install imagemagick
压缩工程目录下所有 png 文件，find . -iname "*.png" -exec echo {} \; -exec convert {} {} \;
使用 find . -iname "*.png" -exec echo {} \; -exec convert {} {} \; 报错
dyld: Library not loaded: /ImageMagick-7.0.7/lib/libMagickCore-7.Q16HDRI.5.dylib
  Referenced from: /Users/xiaojie/Desktop/worlk/ImageMagick-7.0.7/bin/convert
  Reason: image not found

**Comment by xiaojie111** [comment]
可以帮我看下吗

**Comment by xiaojie111** [comment]
identity 可以得到图片信息，压缩不来

**Comment by xiaojie111** [comment]
我是按官网来配的export MAGICK_HOME=/Users/xiaojie/Desktop/worlk/ImageMagick-7.0.7
export DYLD_LIBRARY_PATH=$MAGICK_HOME/lib/
export PATH=$MAGICK_HOME/bin:$PATH
export PATH=$MAGICK_HOME/lib:$PATH解压放在桌面上，指定到桌面

**Comment by klaus01** [comment]
用 brew 安装吧，方便，也不会有那么多问题。

**Comment by xiaojie111** [comment]
用brew怎么安装，有教程吗

**Comment by klaus01** [comment]
https://brew.sh/index_zh-cn

brew 官网
