### ISSUE TITLE
swift 版本生成的代码乱码了，是我配置原因？

### ISSUE THREAD

**Issue by Mebsunny** [klaus01/KLGenerateSpamCode#24]
![1531055457450](https://user-images.githubusercontent.com/16472481/42420111-8cd3a26a-82f3-11e8-853a-c10b24545d23.jpg)
文件名也是错的 里面生成的代码也是乱码

**Comment by klaus01** [comment]
发下调用时的参数看下

**Comment by Dreamhai** [comment]
大佬，好像没有plist方法名文件；
另外那个修改方法名的处理方法在想能不能换个思路呢，这样一修改就会把文件里面的只要包含有设置的关键字的字符串全部替换了，能否只是替换.h里面的方法名呢

**Comment by Mebsunny** [comment]
-spamCodeOut /Users/xiaoxiong/Desktop/TestAPP 
这句话有问题没有加新的类名字 现在已经解决了 非常感谢

**Comment by klaus01** [comment]
@Dreamhai 你可以改一下，欢迎 pull requests
