### ISSUE TITLE
-modifyClassNamePrefix时报错，请问下是什么原因, 错误如下

### ISSUE THREAD

**Issue by rainedAllNight** [klaus01/KLGenerateSpamCode#25]
GenerateSpamCode[39408:68912785] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndexedSubscript:]: index 3 beyond bounds [0 .. 2]

**Comment by rainedAllNight** [comment]
这个问题原因找到了，是路径没有填完整，但是又有一个新问题就是处理完以后工程很多文件被删除了，文件变红了

**Comment by klaus01** [comment]
出现这种情况是改了文件名，但工程文件中的文件名未被修改。
大多出现在第三方库文件或扩展文件，一般来说这些文件应该独立放在“第三方”和“扩展”文件夹中，并设置本工具的`-ignoreDirNames`参数。

这个问题在我的工程中也有，只因为只有几个文件，所以我都是手动修改的。
