### ISSUE TITLE
和你配置的一样，出现如下问题

### ISSUE THREAD

**Issue by huangcheng0908** [klaus01/KLGenerateSpamCode#26]
打开工程文件 /Users/wt/Desktop/QQJXLuckPay_Mains/QQJXLuckPay.xcodeproj/project.pbxproj 失败：The file “project.pbxproj” couldn’t be opened because there is no such file.

**Comment by klaus01** [comment]
可能是这个原因。https://github.com/klaus01/KLGenerateSpamCode/issues/16#issuecomment-406274892
