### ISSUE TITLE
运行没反应

### ISSUE THREAD

**Issue by BillyChen957** [klaus01/KLGenerateSpamCode#3]
可以留个QQ吗

**Comment by klaus01** [comment]
看下日志输出没！

**Comment by LiMing11111** [comment]
工程名  和 .xcassets 没有成功修改

**Comment by klaus01** [comment]
@LiMing11111 和工程目录结构有关，参考下这个 https://github.com/klaus01/KLGenerateSpamCode/issues/9#issuecomment-375892020
