### ISSUE TITLE
这个真的管用？

### ISSUE THREAD

**Issue by zhaohailog** [klaus01/KLGenerateSpamCode#4]
你好，我用你这个修改包的名字的时候就文件夹的名字改了，其余的没有改变。还有，生成的垃圾代码只是一些分类，但是核心文件的方法名，属性名都没改变，只是改变类名了。这个状态真的能过审核？？最近被4.3搞的头大了

**Comment by klaus01** [comment]
修改工程名，会修改文件夹、.xcodeproj、.xcworkspace 的名称，以及 Podfile 里的名称。

垃圾代码主要遍历指定目录下的 .m .swift 文件中的类和方法，在原方法的基础上增加一个参数，然后生成对应类的 Category 文件。

如果工具的使用结果不是预期的那样，那可能是工具不适用于你的工程或使用方式没对。该工具的只在我的工程上跑过，所以其它工程的适应情况不该保证。

本周我有个包也被 4.3 了，看样子苹果的机审又升级了，得考虑添加一些别人手写的对工程没用的代码，然后向包中添加更多的无用文件。
