### ISSUE TITLE
请教。修改类名前缀不成功

### ISSUE THREAD

**Issue by XL-Andrew** [klaus01/KLGenerateSpamCode#40]
![111](https://user-images.githubusercontent.com/17964664/45150118-b23d3c80-b1fd-11e8-89fb-c01a6aa5bfc5.png)

**Comment by klaus01** [comment]
是工具有错误，工具目前不支持一次运行包含改工程名和改类名两个动作。

**Comment by klaus01** [comment]
建议一次运行只执行一个动作。

**Comment by XL-Andrew** [comment]
好的，感谢
