### ISSUE TITLE
如果项目原本就没有类前缀,那改怎么增加类前缀呢?

### ISSUE THREAD

**Issue by TynnPassBy** [klaus01/KLGenerateSpamCode#5]
如题,没有类前缀的想新增的话 怎么写-modifyClassNamePrefix

**Comment by klaus01** [comment]
没有前缀的话，随便写一个及可，如：`-modifyClassNamePrefix "xcodeproj文件路径" xxx>NEWP`。代码逻辑是如果前缀不是 xxx 就在前面加上 NEWP，如果前面是 xxx 开头就用 NEWP 替换 xxx。

**Comment by hms111111** [comment]
不明白,没有前缀,怎么随便写一个啊?代码里面用到怎么办?
