### ISSUE TITLE
请问修改工程名字报下面的错是怎么回事啊

### ISSUE THREAD

**Issue by imdp6** [klaus01/KLGenerateSpamCode#54]
ch 失败：The file “AISHEN-Bridging-Header-swift_1NMN8E27ZXEIF-clang_1D1FZ55LD06AG.pch” couldn’t be opened using text encoding Unicode (UTF-8).

**Comment by klaus01** [comment]
分步执行命令，及每运行一次只做一个动作。试试

**Comment by klaus01** [comment]
参数里面只有`-ignoreDirNames`不是动作，可以和其它动作一起。
