### ISSUE TITLE
添加命令时的问题

### ISSUE THREAD

**Issue by superlu88** [klaus01/KLGenerateSpamCode#55]
-modifyClassNamePrefix /Users/pt 1/Desktop/xxxx/源码/xxxx/xxxx/xxxx.xcodeproj xxxx>xxxxtexts
问一下，我的地址里有一个个人目录的名字是pt 1，有空格，请问怎么解决这个问题，总是提示不存在。

**Comment by klaus01** [comment]
需要转义，试试`/Users/pt\ 1/Desktop`
