### ISSUE TITLE
缺少 NewClass 代码函数调用名

### ISSUE THREAD

**Issue by superlu88** [klaus01/KLGenerateSpamCode#56]
其它都可以，就是生成垃圾代码不行

**Comment by superlu88** [comment]
> 其它都可以，就是生成垃圾代码不行，希望能尽快给我回复，谢谢。

**Comment by klaus01** [comment]
调用参数发出来。另外是编译执行，还是命令行执行？

**Comment by klaus01** [comment]
你打个断点看下吧，看下代码中 gNewClassFuncationCallName 取到值是什么？

**Comment by superlu88** [comment]
gNewClassFuncationCallName里面是：第三方,功能方法；
<img width="769" alt="2018-12-20 14 36 33" src="https://user-images.githubusercontent.com/42953479/50268182-c92e3480-0464-11e9-908f-821163c75792.png">
我之前有看到你在另一个相似的问题中，说是-spamCodeOut有新添加两个参数，但是我这边不知道应该怎么修改，请教！

**Comment by klaus01** [comment]
gNewClassFuncationCallName 就是新增的其中一个参数。

从你的截图来看，是目录中的空格没有转义的原因，第1和3行目录中的空格必需转义，否则会造成参数变多。

**Comment by klaus01** [comment]
另外 -spamCodeOut 的目录最好不是第1行的子目录，可能会造成递归。

**Comment by superlu88** [comment]
我现在使用的-spamCodeOut还只有两个参数，
之前看到你说，生成垃圾代码-spamCodeOut还需要增加两个参数：
-spamCodeOut 垃圾代码文件存放目录 垃圾代码参数名 垃圾代码函数调用名 NewClass代码函数调用名
后面两个要填写什么内容，
希望有一个事例说明：-spamCodeOut /user/xx slkdejfo [垃圾代码函数调用名] [NewClass代码函数调用名]

**Comment by superlu88** [comment]
解决了，必须要加后面两个参数才能成功，谢谢。
