### ISSUE TITLE
垃圾代码没有生成

### ISSUE THREAD

**Issue by zhiyoukaifa** [klaus01/KLGenerateSpamCode#65]
项目报已经生成垃圾代码了 但是实际上没有生成 注释也没有删掉
![image](https://user-images.githubusercontent.com/13886142/55242122-8e177a80-5277-11e9-97bd-037efc7ea083.png)

**Comment by klaus01** [comment]
第一个目录参数设置错误

发自我的 iPhone

**Comment by shurouLei** [comment]
C语言写的能生成垃圾代码嘛，我的项目是c语言的不是o c

**Comment by klaus01** [comment]
不支持

发自我的 iPhone
