### ISSUE TITLE
YouTube Video

### ISSUE THREAD

**Issue by MohammedElbouhali** [klaus01/KLGenerateSpamCode#69]
Please provide us with a youtube video explaining the method, cause i've been trying to implement the method 4days now, with no results !
Appreciate your work, and love yah <3

**Comment by klaus01** [comment]
This method has failed for repeated application shelves.

发自我的 iPhone

**Comment by MohammedElbouhali** [comment]
is it now working anymore ?

**Comment by klaus01** [comment]
No.

The project is no longer updated.
