### ISSUE TITLE
有些不懂的地方

### ISSUE THREAD

**Issue by zhujieshan** [klaus01/KLGenerateSpamCode#9]
我设置完参数 最后一步 GenerateSpamCode是什么
使用二进制文件，在终端中执行 GenerateSpamCode

$ ./GenerateSpamCode \
/Users/kelei/Documents/work/git/projectName/source \
-deleteComments

**Comment by klaus01** [comment]
工具使用有两种方式，`使用源码`和`使用二进制文件，在终端中执行`。

`使用源码`=在 Xcode 中执行。
`使用二进制文件，在终端中执行`=在命令行中执行。

用其中一种方式及可。

**Comment by zhujieshan** [comment]
哦哦 原来 哈哈 那我把要改的工程的地址拉进去了 还是显示缺少目录参数的?

**Comment by zhujieshan** [comment]
![2018-03-24 11 26 31](https://user-images.githubusercontent.com/23182986/37859898-580cabbc-2f56-11e8-8558-c40c9300d628.png)

**Comment by zhujieshan** [comment]
我是这样加的 -spanCodeOut [工程里得一个空文件目录] [随便一个字符串] 然后勾了第一个工程地址 和第四个添加垃圾代码 然后运行project
但是控制台打印的是 生成垃圾代码完成
Program ended with exit code: 0

**Comment by klaus01** [comment]
`Desktop/xcode-ljdzz`这个目录是源代码所在目录么？
能发下 Finder 中的该目录的子目录树结构不？

**Comment by klaus01** [comment]
![image](https://user-images.githubusercontent.com/338228/37864889-c5ed5826-2faf-11e8-895f-c247aa807ce2.png)
图中是我们工程的目录结构，使用工具时会将第一个参数配置成`LOBO`这个文件的路径。

**Comment by zhujieshan** [comment]
好的 我的工程目录填错了 填了最外层的 搞定了
